name: budget_tracker
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter     
  cupertino_icons: ^1.0.6
  http:
  intl: ^0.19.0
  logger:
  url_launcher:
  smooth_page_indicator:
  get:
  get_storage:
  iconsax:
  font_awesome_flutter:
  fl_chart:
  flutter_colorpicker:
  shared_preferences:
  lottie:
  animated_splash_screen:
  flutter_launcher_icons:
  hive:
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator:
  build_runner:

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logos/Logo_foreground.png"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/brands/
    - assets/images/on_boarding_images/Saving.gif
    - assets/images/on_boarding_images/Spending.gif
    - assets/logos/facebook.png
    - assets/logos/google.png
    - assets/logos/Logo.png
    - assets/logos/Logo_foreground.png
    - assets/images/budget/travel.png
    - assets/images/budget/entertainment.png
    - assets/images/budget/food.png
    - assets/images/budget/home.png
    - assets/images/budget/pet.png
    - assets/images/budget/shopping.png
    - assets/images/budget/tech.png
    - assets/logos/splash.json

  fonts:
  - family: RobotoMono
    fonts:
        - asset: assets/fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono-ThinItalic.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono-BoldItalic.ttf
          weight: 700      
