name: movie_ticket
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc:
  flutter_bloc:
  get:
  intl:
  animated_splash_screen:
  flutter_svg:
  simple_gradient_text:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/Illustrations/logo.svg"
  adaptive_icon_foreground: "lib/assets/Illustrations/logo.svg"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/Banners/Movie_banner_1.svg
    - lib/assets/Banners/Movie_banner_2.svg
    - lib/assets/Banners/Movie_banner_1.svg
    - lib/assets/Icons/Add.svg
    - lib/assets/Icons/back.svg
    - lib/assets/Icons/Cancel.svg
    - lib/assets/Icons/Control.svg
    # - lib/assets/Icons/Home_active.svg
    # - lib/assets/Icons/Home_unactive.svg
    - lib/assets/Icons/location.svg
    - lib/assets/Icons/next.svg
    - lib/assets/Icons/Play.svg
    # - lib/assets/Icons/Pocket_active.svg
    # - lib/assets/Icons/Pocket_unactive.svg
    - lib/assets/Icons/Search.svg
    # - lib/assets/Icons/Ticket_active.svg
    # - lib/assets/Icons/Ticket_unactive.svg
    # - lib/assets/Icons/top_up.svg
    - lib/assets/Illustrations/Change_Language.svg
    - lib/assets/Illustrations/Edit_Profile.svg
    - lib/assets/Illustrations/Help_Centre.svg
    - lib/assets/Illustrations/illustration_1.svg
    - lib/assets/Illustrations/illustration_2.svg
    - lib/assets/Illustrations/logo.svg
    - lib/assets/Illustrations/My_Wallet.svg
    - lib/assets/Illustrations/photo_profile.svg
    - lib/assets/Illustrations/Rate_Flutix_App.svg
    - lib/assets/Illustrations/Rating.svg
    - lib/assets/Images/Cast/Gal.svg
    - lib/assets/Images/Cast/John.svg
    - lib/assets/Images/Cast/Jack.svg
    - lib/assets/Images/Cast/Sarah.svg
    - lib/assets/Images/Cast/Taraji.svg
    - lib/assets/Images/Image/Barcode.svg
    - lib/assets/Images/Movie_poster/Dragon.svg
    - lib/assets/Images/Movie_poster/Frozen.svg
    - lib/assets/Images/Movie_poster/Onward.svg
    - lib/assets/Images/Movie_poster/Ralph.svg
    - lib/assets/Images/Movie_poster/Scoob.svg
    - lib/assets/Images/Movie_poster/Spongebob.svg
    - lib/assets/Images/photo/profile.svg
    - lib/assets/Images/Trailer/trailer_1.svg
    - lib/assets/Images/Trailer/trailer_2.svg
    - lib/assets/Images/Button/Facebook.svg
    - lib/assets/Images/Button/Google.svg

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/Fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: lib/assets/Fonts/Montserrat-ThinItalic.ttf
          weight: 100
        - asset: lib/assets/Fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/Fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
        - asset: lib/assets/Fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/assets/Fonts/Montserrat-LightItalic.ttf
          weight: 300
        - asset: lib/assets/Fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/assets/Fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/Fonts/Montserrat-MediumItalic.ttf
          weight: 500
        - asset: lib/assets/Fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/assets/Fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
        - asset: lib/assets/Fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/Fonts/Montserrat-BoldItalic.ttf
          weight: 700
