name: movie_ticket
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc:
  flutter_bloc:
  get:
  intl:
  animated_splash_screen:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/Illustrations/logo.png"
  adaptive_icon_foreground: "lib/assets/Illustrations/logo.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/Banners/Movie_banner_1.png
    - lib/assets/Banners/Movie_banner_2.png
    - lib/assets/Banners/Movie_banner_1.png
    - lib/assets/Icons/Add.png
    - lib/assets/Icons/back.png
    - lib/assets/Icons/Cancel.png
    - lib/assets/Icons/Control.png
    - lib/assets/Icons/Home_active.png
    - lib/assets/Icons/Home_unactive.png
    - lib/assets/Icons/location.png
    - lib/assets/Icons/next.png
    - lib/assets/Icons/Play.png
    - lib/assets/Icons/Pocket_active.png
    - lib/assets/Icons/Pocket_unactive.png
    - lib/assets/Icons/Search.png
    - lib/assets/Icons/Ticket_active.png
    - lib/assets/Icons/Ticket_unactive.png
    - lib/assets/Icons/top_up.png
    - lib/assets/Illustrations/Change_Language.png
    - lib/assets/Illustrations/Edit_Profile.png
    - lib/assets/Illustrations/Help_Centre.png
    - lib/assets/Illustrations/illustration_1.png
    - lib/assets/Illustrations/illustration_2.png
    - lib/assets/Illustrations/logo.png
    - lib/assets/Illustrations/My_Wallet.png
    - lib/assets/Illustrations/photo_profile.png
    - lib/assets/Illustrations/Rate_Flutix_App.png
    - lib/assets/Illustrations/Rating.png
    - lib/assets/Images/Cast/Gal.png
    - lib/assets/Images/Cast/John.png
    - lib/assets/Images/Cast/Jack.png
    - lib/assets/Images/Cast/Sarah.png
    - lib/assets/Images/Cast/Taraji.png
    - lib/assets/Images/Image/Barcode.png
    - lib/assets/Images/Movie_poster/Dragon.png
    - lib/assets/Images/Movie_poster/Frozen.png
    - lib/assets/Images/Movie_poster/Onward.png
    - lib/assets/Images/Movie_poster/Ralph.png
    - lib/assets/Images/Movie_poster/Scoob.png
    - lib/assets/Images/Movie_poster/Spongebob.png
    - lib/assets/Images/photo/profile.png
    - lib/assets/Images/Trailer/trailer_1.png
    - lib/assets/Images/Trailer/trailer_2.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/Fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: lib/assets/Fonts/Montserrat-ThinItalic.ttf
          weight: 100
        - asset: lib/assets/Fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/Fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
        - asset: lib/assets/Fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/assets/Fonts/Montserrat-LightItalic.ttf
          weight: 300
        - asset: lib/assets/Fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/assets/Fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/Fonts/Montserrat-MediumItalic.ttf
          weight: 500
        - asset: lib/assets/Fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/assets/Fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
        - asset: lib/assets/Fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/Fonts/Montserrat-BoldItalic.ttf
          weight: 700
