name: ums
description: "University Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen:
  flutter_svg:
  flutter_bloc:
  bloc:
  equatable:
  page_transition:
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/images/logo.svg
  - assets/images/avatar.svg
  - assets/images/onboarding_1.gif
  - assets/images/onboarding_2.gif
  - assets/images/onboarding_3.gif

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/Fonts/Montserrat-ThinItalic.ttf
          weight: 100
        - asset: assets/Fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/Fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/Fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/Fonts/Montserrat-LightItalic.ttf
          weight: 300
        - asset: assets/Fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Montserrat-MediumItalic.ttf
          weight: 500
        - asset: assets/Fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/Fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/Fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Montserrat-BoldItalic.ttf
          weight: 700